name: Update Gist

on:
  push:
    branches:
      - main
    paths:
      - main.py

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Gist
        run: |
          GIST_ID="0bf318155cf9c4b51021c6259aa9ba76"
          FILE_PATH="main.py"
          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d "$(jq -n --arg content "$(cat $FILE_PATH)" '{"files": {"main.py": {"content": $content}}}')" \
            https://api.github.com/gists/$GIST_ID
